#!/usr/bin/dash

default="awesome";
cmd="${2:-"$default"}";

case "$cmd" in

  dwmalt)
    xsetroot -cursor_name left_ptr&
    hsetroot -solid '#121212'&
    rm -f /tmp/.dwm.keepalive&
    xset r rate 300 30&
    xset m 5/1 10&
    {
      id="$(xinput --list --id-only 'ELAN1200:00 04F3:30BA Touchpad')";
      xinput set-prop $id 'libinput Disable While Typing Enabled' 0;
      xinput set-prop $id 'libinput Horizontal Scroll Enabled' 1;
      xinput set-prop $id 'libinput Tapping Enabled' 0;
      xinput set-prop $id 'libinput Accel Speed' '0.55';

      xmodmap -e "keysym F1 = Pointer_Button1 Pointer_Button1 Pointer_Button1 Pointer_Button1"
      xmodmap -e "keysym F2 = Pointer_Button2 Pointer_Button2 Pointer_Button2 Pointer_Button2"
      xmodmap -e "keysym F3 = Pointer_Button3 Pointer_Button3 Pointer_Button3 Pointer_Button3"

      xmodmap -e "keysym Alt_L = Pointer_Button3 Pointer_Button3 Pointer_Button3 Pointer_Button3"
      # xmodmap -e "keysym Space = Pointer_Button3 Pointer_Button3 Pointer_Button3 Pointer_Button3"

      xkbset m
      xkbset exp '=m'

      xrdb "$HOME/.Xresources"
      light -S 30

    }&
    { exec "dwm"; exit "$?"; }

esac

if [ -f "$HOME/.Xresources" ];
then
  xrdb "$HOME/.Xresources"&
fi;
urxvtd -q -f -o
# picom --experimental-backends -b

# nm-applet&

{ redshift -x; redshift -r -P & }&

if [ -f "$HOME/scripts/mouse_kbd_setup" ];
then
  "$HOME/scripts/mouse_kbd_setup"&
fi;

exec "$cmd";

# vim: set ft=sh:
