#!/usr/bin/env bash

$HOME/scripts/mouse_kbd_setup.sh &
$HOME/.fehbg &
picom -b --experimental-backends
pgrep -x nm-applet || nm-applet &
pgrep -x redshift-gtk || redshift-gtk &
pgrep -x dunst || dunst &
pgrep -x sxhkd || sxhkd &
pgrep -x xautolock || xautolock -secure -time 10 -corners '00-+' -cornerdelay 1 -cornerredelay 60 -locker slock &
pgrep -x polybar || $HOME/.config/polybar/launch-bspwm.sh
xsetroot -cursor_name left_ptr &
# pgrep -x xbanish || xbanish &

# novum
bspc config normal_border_color         '#808080'
bspc config active_border_color         '#afd7af'
bspc config focused_border_color        '#87afd7'
bspc config presel_feedback_color       '#af8787'

bspc config split_ratio                 0.5
# bspc config status_prefix               ''
# bspc config external_rules_command      ''
bspc config initial_polarity            'second_child'
bspc config directional_focus_tightness 'low'
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config paddingless_monocle         false
bspc config single_monocle              false
bspc config pointer_motion_interval     20
bspc config pointer_modifier            'mod4'
bspc config pointer_action1             'move'           # left
bspc config pointer_action2             'focus'          # middle
bspc config pointer_action3             'resize_corner'  # right
bspc config click_to_focus              false
bspc config swallow_first_click         false
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     false
bspc config ignore_ewmh_focus           false
bspc config center_pseudo_tiled         true
bspc config honor_size_hints            true
bspc config remove_disabled_monitors    false
bspc config remove_unplugged_monitors   false
bspc config merge_overlapping_monitors  false

# Monitor and Desktop Settings
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bspc config top_padding             32
bspc config right_padding           0
bspc config bottom_padding          0
bspc config left_padding            0

# Desktop Settings
# ~~~~~~~~~~~~~~~~
bspc config window_gap              3

# Node Settings
# ~~~~~~~~~~~~~
bspc config border_width            1

# Monitors
# ~~~~~~~~
bspc monitor -d term web code school 5 6 7 8 web chat

# Rules
# ~~~~~
while [[ $(bspc rule -l | wc -l) -gt 0 ]]; do
	bspc rule -r head;
done;
# bspc rule -a Gimp desktop=^8 follow=off
# bspc rule -a Firefox desktop=^2 follow=off
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a '*LibreOffice*' state=tiled
# bspc rule -a Screenkey manage=off

# bspc config border_width 3
# bspc config window_gap -3
# bspc config top_padding 3
# bspc config right_padding 3
# bspc config bottom_padding 3
# bspc config left_padding 3

