#!/bin/sh

if [ -d /sys/class/power_supply/ ]; then
  current_charge="$(cat /sys/class/power_supply/*/charge_now)";
  total_charge="$(cat /sys/class/power_supply/*/charge_full)";
elif [ -d /proc/acpi/battery/ ]; then
  current_charge=$(cat /proc/acpi/battery/*/state | grep 'remaining capacity' | awk '{print $3}');
  total_charge=$(cat /proc/acpi/battery/*/info | grep 'last full capacity' | awk '{print $4}');
fi;

i='?';
STATUS="$(cat /sys/class/power_supply/*/status)";
if [ "$STATUS" = "Charging" ];
then
  i='↑ ';
elif [ "$STATUS" = "Discharging" ];
then
  i='↓ ';
elif [ "$STATUS" = "Full" ];
then
  i='full';
fi;

printf "%s %0.2f%%\n" "$i" "$(echo "(($current_charge/$total_charge)*100)" | bc -l)";

