#!/usr/bin/env python3
# -*- coding: utf-8 -*-

r"""
           {1} _______________________________________________________ {0}
           {1}| | |__   __ _           _____      _(_) |_ ___| |__    \{0}
           {1}| | '_ \ / _` |         / __\ \ /\ / / | __/ __| '_ \   |{0}
           {1}| | |_) | (_| |         \__ \\ V  V /| | || (__| | | |  |{0}
           {1}| |_.__/ \__, |  _____  |___/ \_/\_/ |_|\__\___|_| |_|  |{0}
           {1} \_______|___/__|_____|_________________________________|{0}

                      {2} oO)-.                       .-(Oo {0}
                      {2}/__  _\                     /_  __\{0}
                      {2}\  \(  |     ()~()         |  )/  /{0}
                      {2} \__|\ |    (-___-)        | /|__/ {0}
                      {2} '  '--'    ==`-'==        '--'  ' {0}

                           {3}easily switch backgrounds{0}
"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter as raw_help

doc_colors = ('\x1b[0m', '\x1b[34;1m', '\x1b[32m', '\x1b[3;1;33m')
    
def main():
    doc = __doc__.format(*doc_colors)

    parser = ArgumentParser(
        description=doc,
        formatter_class=raw_help,
        epilog='{1}linux only{0} with {1}dependencies: {2}feh{0}'.format(
            '\x1b[0m', '\x1b[1m', '\x1b[34;1m')
                )

    args = parser.parse_args()

    if args.help:
        parser.print_help()
        exit(0)

if __name__ == "__main__":
    main()
