#!/bin/sh

if [ -r /tmp/newzathura.id ]; then
  read -r id </tmp/newzathura.id;
  zathura --fork "$@" -e "$id";
else
  {
    tabbed -c >/tmp/newzathura.id &
    tid="$!";
    i=0;
    while [ ! -s /tmp/newzathura.id ];
    do
      if [ "$i" -gt 200 ];
      then
        kill "$tid";
        exit 1;
      fi;
      i="$((i+1))";
      sleep 0.01;
    done;
    read -r id </tmp/newzathura.id;
    zathura --fork "$@" -e "$id";
    wait;
    rm -f /tmp/newzathura.id;
  } &
fi;

