#!/usr/bin/env bash

[ -s /tmp/newzathura-nofork ] && { zathura --fork $@; return; }

if [ -f /tmp/newzathura.xid ]; then
	zathura --fork "$@" -e $(</tmp/newzathura.xid);
else
	( {
		tabbed -c >/tmp/newzathura.xid &
		tpid=$!;
		f=0;
		for i in {1..10}; do
			sleep 0.01;
			[ -s /tmp/newzathura.xid ] || continue;
			zathura --fork $@ -e $(</tmp/newzathura.xid);
			f=1;
			break;
		done;
		[ "$f" -eq 0 ] && kill $tpid;
		wait;
		rm -f /tmp/newzathura.xid;
	} &);
fi;

