#!/usr/bin/bash

# EXPLANATION:
#   1) click floating window
#   2) click+drag to draw rectangle and reshape window to rectangle

# NOTE: this doesn't seem to work in desktop environments like xfce4

# DEPENDENCIES:
#   bash, grep, cut
#   xwininfo, slop, xdotool, xdo

rid="$(xwininfo -root | grep 'Window id:' | cut -d' ' -f4)"
I="$(xwininfo | grep 'Window id:' | cut -d' ' -f4)"
[[ $I == $rid ]] && return 1
eval "$(xdotool getwindowfocus getwindowgeometry --shell)"
WX="$X"
WY="$Y"
read -r TX TY TW TH < <(slop -kf "%x %y %w %h")
eval "$(xdotool getmouselocation --shell)"

xdotool mousemove "$WX" "$WY"
xdo resize -t"$I" -w"$TW" -h"$TH"
xdo move -t"$I" -x"$TX" -y"$TY"
xdotool mousemove "$X" "$Y"
