#!/bin/sh

e=$'\e['

# function pc(){
#     if [ "$n" -lt "10" ]; then
#         w=44
#     elif [ "$n" -lt 100 ]; then
#         w=47
#     else
#         w=50
#     fi
#     printf "%-${w}s" "${e}48;05;${n}m|${e}0;38;05;${n}m${n}${e}0;48;05;${n}m|${e}0m "
# }

pc(){
  printf "\\033[38;05;${1}m%-6s" "($1) ";
}

n=0;
while [ "$n" -le 7 ];
do
  pc "$n";
  n="$((n+1))";
done;
printf '\n';

n=8;
while [ "$n" -le 15 ];
do
    pc "$n";
    n="$((n+1))";
done;
printf '\n';

