#!/bin/sh

if [ -d /sys/class/power_supply/ ]; then
    current_charge="$(cat /sys/class/power_supply/*/charge_now)";
    total_charge="$(cat /sys/class/power_supply/*/charge_full)";
elif [ -d /proc/acpi/battery/ ]; then
    current_charge=$(cat /proc/acpi/battery/*/state | grep 'remaining capacity' | awk '{print $3}');
    total_charge=$(cat /proc/acpi/battery/*/info | grep 'last full capacity' | awk '{print $4}');
fi;

charge="$(printf "($current_charge/$total_charge)*100\n" | bc -l)";
status="$(cat /sys/class/power_supply/*/status)";

if [ "$status" = "Charging" ]; then
    printf '#[fg=magenta] ';
elif [ "$status" = "Discharging" ]; then
	if [ "$(printf "$charge < 15\n" | bc -l)" -eq 1 ]; then
		printf '#[fg=red]  ';
	elif [ "$(printf "$charge < 40\n" | bc -l)" -eq 1 ]; then
		printf '#[fg=yellow]  ';
	elif [ "$(printf "$charge < 60\n" | bc -l)" -eq 1 ]; then
		printf '#[fg=cyan]  ';
	elif [ "$(printf "$charge < 80\n" | bc -l)" -eq 1 ]; then
		printf '#[fg=green]  ';
	else
		printf '#[fg=blue]  ';
	fi
elif [ "$status" = "Full" ]; then
	printf '#[fg=blue]   100%%';
	exit 0;
else
    printf '#[fg=magenta]?[%s] ' "$status"
fi;
printf '%0.2f%%' "$charge";
